-- Player.script
local speed = 20.0

function init(self)
	print("PLAYER INIT RAN")
	msg.post(".", "acquire_input_focus")
	self.input = vmath.vector3(0, 0, 0)
	self.moving = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("ray_cast_response") then
		local pos = go.get_position()
		local target_y = message.position.y
		--print(target_y)
		pos.y = pos.y + (target_y - pos.y) * 0.3
		go.set_position(pos)
		
	elseif message_id == hash("ray_cast_missed") then
		print("Ray missed - no ground detected under player")
		-- we'll fill this in next
		
	elseif message_id == hash("contact_point_response") then
		if math.abs(message.normal.y) < 0.5 then
			print("push", message.normal.x, message.normal.y, message.normal.z, message.distance)
			local pos = go.get_position()
			local normal = message.normal * message.distance
			go.set_position(pos + normal)
		end
	end
end


function update(self, dt)
	-- Convert flat input into isometric world directions
	local move = vmath.vector3(0, 0, 0)
	move.x = move.x + (self.input.x - self.input.y)
	move.z = move.z + (self.input.x + self.input.y) * -1
	if vmath.length(move) > 0 then
		move = vmath.normalize(move)
	end
	
	local is_moving = vmath.length(move) > 0
	if is_moving and not self.moving then
		print("play anim")
		model.play_anim("#model", "Armature|mixamo.com|Layer0", go.PLAYBACK_LOOP_FORWARD)
	elseif not is_moving and self.moving then
		model.cancel("#model")
	end
	
	self.moving = is_moving
	local pos = go.get_position()
	pos = pos + move * speed * dt

	local ray_height = 10.0
	local ray_depth = 20.0
	local from = vmath.vector3(pos.x, pos.y + ray_height, pos.z)
	local to = vmath.vector3(pos.x, pos.y - ray_depth, pos.z)
	physics.raycast_async(from, to, {hash("Environment")})

	go.set_position(pos)
	self.input = vmath.vector3(0, 0, 0)
end

function on_input(self, action_id, action)
	--print("input:", action_id)
	print("PLAYER ON_INPUT:", action_id)
	if action_id == hash("up") then
		self.input.y = 1
	elseif action_id == hash("down") then
		self.input.y = -1
	elseif action_id == hash("right") then
		self.input.x = 1
	elseif action_id == hash("left") then
		self.input.x = -1
	end
end