function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.enter then
			msg.post("/Environment#lib_GroundFront", "disable")
			msg.post("/Environment#Lib_roof", "disable")
			msg.post("/Environment#Lib_roofcap", "disable")
		else
			msg.post("/Environment#lib_GroundFront", "enable")
			msg.post("/Environment#Lib_roof", "enable")
			msg.post("/Environment#Lib_roofcap", "enable")	
		end
	end	
end